"""Markdown renderer - Generate human-readable Markdown from bundles."""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from bugsafe.bundle.schema import BugBundle, Frame, Traceback


def _format_command(command: list[str]) -> str:
    """Format command for display."""
    if not command:
        return "<no command>"
    return " ".join(command)


def _format_traceback_frame(frame: Frame) -> str:
    """Format a single traceback frame."""
    location = f'  File "{frame.file}", line {frame.line}'
    if frame.function:
        location += f", in {frame.function}"

    lines = [location]
    if frame.code:
        lines.append(f"    {frame.code}")

    if frame.locals:
        for name, value in frame.locals.items():
            lines.append(f"        {name} = {value}")

    return "\n".join(lines)


def _format_traceback(tb: Traceback) -> str:
    """Format a complete traceback."""
    lines = ["Traceback (most recent call last):"]

    for frame in tb.frames:
        lines.append(_format_traceback_frame(frame))

    lines.append(f"{tb.exception_type}: {tb.message}")

    return "\n".join(lines)


def _format_timestamp(dt: datetime) -> str:
    """Format datetime for display."""
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def _format_packages(packages: list[dict[str, str]]) -> str:
    """Format packages list for display."""
    if not packages:
        return "No packages recorded"

    lines = []
    for pkg in packages:
        name = pkg.get("name", "unknown")
        version = pkg.get("version", "unknown")
        lines.append(f"{name}=={version}")

    return "\n".join(sorted(lines))


def _format_redaction_table(report: dict[str, int]) -> str:
    """Format redaction report as a table."""
    if not report:
        return "No secrets were redacted."

    lines = ["| Category | Count |", "|----------|-------|"]
    total = 0
    for category, count in sorted(report.items()):
        lines.append(f"| {category} | {count} |")
        total += count

    lines.append(f"| **Total** | **{total}** |")
    return "\n".join(lines)


def _format_env_table(env_vars: dict[str, str]) -> str:
    """Format environment variables as a table."""
    if not env_vars:
        return "No environment variables recorded."

    lines = ["| Variable | Value |", "|----------|-------|"]
    for key, value in sorted(env_vars.items()):
        safe_value = value.replace("|", "\\|")
        if len(safe_value) > 60:
            safe_value = safe_value[:57] + "..."
        lines.append(f"| `{key}` | `{safe_value}` |")

    return "\n".join(lines)


def render_markdown(bundle: BugBundle) -> str:
    """Render a BugBundle as Markdown.

    Args:
        bundle: The bundle to render.

    Returns:
        Markdown string.
    """
    sections: list[str] = []

    sections.append("# Bug Report")
    sections.append("")
    sections.append(f"**Generated by:** bugsafe v{bundle.metadata.bugsafe_version}")
    sections.append(f"**Created:** {_format_timestamp(bundle.metadata.created_at)}")
    sections.append("")

    sections.append("## Command")
    sections.append("")
    sections.append("```bash")
    sections.append(_format_command(bundle.capture.command))
    sections.append("```")
    sections.append("")

    sections.append(f"**Exit code:** {bundle.capture.exit_code}")
    sections.append(f"**Duration:** {bundle.capture.duration_ms}ms")
    if bundle.capture.timed_out:
        sections.append("**Status:** Timed out")
    sections.append("")

    if bundle.traceback:
        sections.append("## Error")
        sections.append("")
        sections.append("```")
        exc = f"{bundle.traceback.exception_type}: {bundle.traceback.message}"
        sections.append(exc)
        sections.append("```")
        sections.append("")

        sections.append("## Traceback")
        sections.append("")
        sections.append("```python")
        sections.append(_format_traceback(bundle.traceback))
        sections.append("```")
        sections.append("")

    if bundle.capture.stderr:
        sections.append("## Standard Error")
        sections.append("")
        sections.append("```")
        stderr = bundle.capture.stderr
        if len(stderr) > 5000:
            stderr = stderr[:5000] + "\n... (truncated)"
        sections.append(stderr)
        sections.append("```")
        sections.append("")

    if bundle.capture.stdout:
        sections.append("<details>")
        sections.append("<summary>Standard Output</summary>")
        sections.append("")
        sections.append("```")
        stdout = bundle.capture.stdout
        if len(stdout) > 5000:
            stdout = stdout[:5000] + "\n... (truncated)"
        sections.append(stdout)
        sections.append("```")
        sections.append("")
        sections.append("</details>")
        sections.append("")

    if bundle.environment:
        sections.append("## Environment")
        sections.append("")
        sections.append("| Key | Value |")
        sections.append("|-----|-------|")
        py_ver = bundle.environment.python_version.split()[0]
        sections.append(f"| Python | `{py_ver}` |")
        sections.append(f"| Platform | `{bundle.environment.platform}` |")

        if bundle.environment.git:
            git = bundle.environment.git
            if git.ref:
                ref_short = git.ref[:7] if len(git.ref) > 7 else git.ref
                dirty = " (dirty)" if git.dirty else ""
                sections.append(f"| Git | `{ref_short}{dirty}` |")
            if git.branch:
                sections.append(f"| Branch | `{git.branch}` |")

        if bundle.environment.virtualenv:
            sections.append("| Virtualenv | Yes |")
        if bundle.environment.ci_detected:
            sections.append("| CI | Yes |")
        if bundle.environment.in_container:
            sections.append("| Container | Yes |")

        sections.append("")

        if bundle.environment.packages:
            pkg_list = [
                {"name": p.name, "version": p.version}
                for p in bundle.environment.packages
            ]
            sections.append("<details>")
            sections.append(f"<summary>Installed Packages ({len(pkg_list)})</summary>")
            sections.append("")
            sections.append("```")
            sections.append(_format_packages(pkg_list))
            sections.append("```")
            sections.append("")
            sections.append("</details>")
            sections.append("")

        if bundle.environment.env_vars:
            sections.append("<details>")
            sections.append("<summary>Environment Variables</summary>")
            sections.append("")
            sections.append(_format_env_table(bundle.environment.env_vars))
            sections.append("")
            sections.append("</details>")
            sections.append("")

    if bundle.environment and bundle.environment.git and bundle.environment.git.ref:
        sections.append("## Reproduction Steps")
        sections.append("")
        sections.append(f"1. Checkout commit `{bundle.environment.git.ref[:7]}`")
        sections.append("2. Set up environment and install dependencies")
        sections.append(f"3. Run: `{_format_command(bundle.capture.command)}`")
        sections.append("")

    if bundle.redaction_report:
        sections.append("## Redaction Summary")
        sections.append("")
        sections.append(_format_redaction_table(bundle.redaction_report))
        sections.append("")

    return "\n".join(sections)
